name: 'Test: Scoop install'

on:
  pull_request:
  push:
    branches:
      - master

#permissions:
#  id-token: write
#  contents: read

jobs:
  test-build:
    runs-on: windows-latest
    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#        with:
#          fetch-depth: 0
#
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
#          cache: 'maven'

      - name: Install scoop
        uses: MinoruSekine/setup-scoop@v4
      - name: Install streamx
        run: |
          scoop bucket add streamx-dev https://github.com/jgardo-ds/scoop-poc.git
          scoop install streamx
