name: 'Test: Scoop install'

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test-build:
    runs-on: windows-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install scoop
        uses: MinoruSekine/setup-scoop@v4
      - name: Install jgardo-example-app
        run: |
          scoop bucket add streamx-dev https://github.com/jgardo-ds/scoop-poc.git
          scoop install jgardo
          jgardo world
